development:
  adapter: postgresql
  database: odot_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: odot_test
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: odot_production
  pool: 5
  timeout: 5000
  host: localhost
